# Installation
~~~~
pip install tensorflow
~~~~

![](http://www.pyimagesearch.com/wp-content/uploads/2016/11/keras_tf_install_process.jpg)
***
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-002.jpg)
***
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-003.jpg)

# import tensorflow

In [2]:
import tensorflow as tf
tf.__version__
sess = tf.InteractiveSession() # for notebook
# sess = tf.Session()

# Hello A-lab!

In [29]:
hello = tf.constant('Hello, A-lab!')
print("hello = tf.constant('Hello, A-lab!')")  
print(hello, "\n")  

result = sess.run(hello)

print("result = sess.run(hello)")  
print(result)                                 
print(type(result),'\n')     

print(result.decode(encoding='utf-8'))        
print(type(result.decode(encoding='utf-8')),'\n')



hello = tf.constant('Hello, A-lab!')
Tensor("Const_29:0", shape=(), dtype=string) 

result = sess.run(hello)
b'Hello, A-lab!'
<class 'bytes'> 

Hello, A-lab!
<class 'str'> 



# Everyting is operation!

In [17]:
a = tf.constant(1)
b = tf.constant(2)

c = a + b

print(c)
print(c.eval())
print((a*b).eval())
print(c+1)

Tensor("add_9:0", shape=(), dtype=int32)
3
2
Tensor("add_10:0", shape=(), dtype=int32)


# Placeholder

In [31]:
a = tf.placeholder(tf.int64)
b = tf.placeholder(tf.int64)

# 값을 갖고있진 않지만 변수로 지정함
add = tf.add(a, b)
mul = tf.multiply(a, b)

print("add %i" % sess.run(add, feed_dict={a: 1, b: 2}))
print("mul %i" % sess.run(mul, feed_dict={a: 20, b: 3}))

add 3
mul 60


# Linear Regression
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-011.jpg)

In [49]:
# X and Y data
X = [1, 2, 3]
Y = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# XW+b
hypothesis = X * W + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

print("step\tcost\t\tW\t\tb")
# Fit the line
for step in range(2001):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train])

    if step % 200 == 0:
        print(step, "\t", cost_val, "\t", W_val, "\t", b_val)
        
        
# Testing our model
# ????????????????????

step	cost		W		b
0 	 1.64153 	 [ 0.71118176] 	 [-0.53835577]
100 	 0.0105786 	 [ 1.1191659] 	 [-0.27090141]
200 	 0.00653694 	 [ 1.093678] 	 [-0.21295215]
300 	 0.00403943 	 [ 1.07363939] 	 [-0.16739981]
400 	 0.00249611 	 [ 1.0578872] 	 [-0.13159133]
500 	 0.00154245 	 [ 1.04550469] 	 [-0.10344274]
600 	 0.000953138 	 [ 1.03577077] 	 [-0.08131538]
700 	 0.000588985 	 [ 1.02811921] 	 [-0.06392144]
800 	 0.000363956 	 [ 1.02210426] 	 [-0.05024803]
900 	 0.000224899 	 [ 1.01737571] 	 [-0.03949919]
1000 	 0.000138973 	 [ 1.013659] 	 [-0.03104993]
1100 	 8.5876e-05 	 [ 1.01073706] 	 [-0.02440807]
1200 	 5.3067e-05 	 [ 1.00844038] 	 [-0.01918697]
1300 	 3.27928e-05 	 [ 1.00663507] 	 [-0.01508286]
1400 	 2.02642e-05 	 [ 1.00521576] 	 [-0.01185646]
1500 	 1.2522e-05 	 [ 1.00410008] 	 [-0.00932036]
1600 	 7.73802e-06 	 [ 1.00322306] 	 [-0.00732666]
1700 	 4.78181e-06 	 [ 1.00253379] 	 [-0.00575961]
1800 	 2.95529e-06 	 [ 1.00199187] 	 [-0.00452782]
1900 	 1.8265e-06 	 [ 1.00156593] 	 [-0.003559

# with placeholder and feed_dict

In [3]:
# X and Y data
# X = [1, 2, 3]
# Y = [1, 2, 3]
X = tf.placeholder(tf.float32, shape=[None])
Y = tf.placeholder(tf.float32, shape=[None])

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# XW+b
hypothesis = X * W + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

print("step\tcost\t\tW\t\tb")
# Fit the line
for step in range(2001):
#     cost_val, W_val, b_val, _ = sess.run([cost, W, b, train])

    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train],
                                         feed_dict={X: [1, 2, 3], Y: [1, 2, 3]})
    if step % 200 == 0:
        print(step, "\t", cost_val, "\t", W_val, "\t", b_val)
        
        
# Testing our model
print("\nPred 1:", sess.run(hypothesis, feed_dict={X: [5]}))
print("Pred 2:", sess.run(hypothesis, feed_dict={X: [2.5]}))
print("Pred 3:", sess.run(hypothesis, feed_dict={X: [1.5, 3.5]}))


step	cost		W		b
0 	 0.103468 	 [ 1.3277986] 	 [-0.51699817]
200 	 0.0168931 	 [ 1.15059328] 	 [-0.34233364]
400 	 0.0064506 	 [ 1.09305739] 	 [-0.2115414]
600 	 0.00246316 	 [ 1.05750382] 	 [-0.13071971]
800 	 0.000940554 	 [ 1.03553391] 	 [-0.08077682]
1000 	 0.000359152 	 [ 1.02195787] 	 [-0.04991526]
1200 	 0.000137141 	 [ 1.01356864] 	 [-0.03084468]
1400 	 5.23677e-05 	 [ 1.00838459] 	 [-0.01906008]
1600 	 1.99965e-05 	 [ 1.00518119] 	 [-0.01177794]
1800 	 7.63566e-06 	 [ 1.00320172] 	 [-0.00727813]
2000 	 2.91616e-06 	 [ 1.00197864] 	 [-0.00449772]

Pred 1: [ 5.00539589]
Pred 2: [ 2.50044894]
Pred 3: [ 1.49847019  3.50242734]


# Multivariable Linear Regression
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-026.jpg)
***
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-027.jpg)
***
![](https://github.com/zooicl/study_tensorflow/raw/master/00_Slides/images/season1-lab-all/season1-lab-all-029.jpg)

In [55]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  68875.0 
Prediction:
 [[ -80.2456665 ]
 [ -96.07713318]
 [ -94.9462738 ]
 [-103.25806427]
 [ -73.13221741]]
10 Cost:  1.89061 
Prediction:
 [[ 151.90769958]
 [ 182.96092224]
 [ 179.99104309]
 [ 196.14198303]
 [ 139.7051239 ]]
20 Cost:  1.25488 
Prediction:
 [[ 152.60639954]
 [ 183.80773926]
 [ 180.8217926 ]
 [ 197.046875  ]
 [ 140.3526001 ]]
30 Cost:  1.24967 
Prediction:
 [[ 152.60482788]
 [ 183.81285095]
 [ 180.82319641]
 [ 197.0486145 ]
 [ 140.35806274]]
40 Cost:  1.24449 
Prediction:
 [[ 152.60115051]
 [ 183.81542969]
 [ 180.82211304]
 [ 197.04763794]
 [ 140.36157227]]
50 Cost:  1.23935 
Prediction:
 [[ 152.59747314]
 [ 183.81794739]
 [ 180.82099915]
 [ 197.04664612]
 [ 140.36506653]]
60 Cost:  1.23422 
Prediction:
 [[ 152.59381104]
 [ 183.82049561]
 [ 180.81991577]
 [ 197.04566956]
 [ 140.36856079]]
70 Cost:  1.22912 
Prediction:
 [[ 152.59014893]
 [ 183.82301331]
 [ 180.81880188]
 [ 197.04466248]
 [ 140.37203979]]
80 Cost:  1.22406 
Prediction:
 [[ 152.58648682]
 [ 183.8